name: flutter_doc_scanner
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  pdf: ^3.10.4
  file_saver: ^0.2.5
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.1
  flutter_pdfview: ^1.3.1
  uuid: ^4.4.2
  image: ^4.1.3
  image_picker: ^1.0.4
  reorderable_grid_view: ^2.0.0
  mime_type: ^1.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  google_sign_in: ^6.1.5
  googleapis: ^12.0.0
  http: ^1.1.0
  path: ^1.8.3
  flutter_cache_manager: ^3.4.1
  progress_dialog_null_safe: ^3.0.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  
  # AI Summarization Dependencies
  flutter_gemma: ^0.10.1
  crypto: ^3.0.3
  
  # OCR Dependencies for text extraction from scanned PDFs
  google_mlkit_text_recognition: ^0.13.0
  # Using pdfx instead of pdf_render to avoid NDK issues
  pdfx: ^2.6.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.shirsh.flutter_doc_scanner
        pluginClass: FlutterDocScannerPlugin
      ios:
        pluginClass: SwiftFlutterDocScannerPlugin
      linux:
        pluginClass: FlutterDocScannerPlugin
      macos:
        pluginClass: FlutterDocScannerPlugin
      windows:
        pluginClass: FlutterDocScannerPluginCApi
      web:
        pluginClass: FlutterDocScannerWeb
        fileName: flutter_doc_scanner_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/nsu_logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
